import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <main className="min-h-screen bg-[var(--color-primary)]  min-w-full grid grid-rows-[auto,1fr,60px] ">
          <Navbar />
          <section className="max-w-xl mx-auto  text-white">
            {children}
          </section>
          <Footer />
        </main>
      </body>
    </html>
  );
}
