import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer, Navbar, Provider } from "@/components";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <main className="min-h-screen bg-[var(--color-primary)]  min-w-full grid grid-rows-[auto,1fr,60px] ">
          <Provider>
            <Navbar />
            <section className="max-w-xl mx-auto  text-white">
              {children}

              <ToastContainer
                pauseOnHover={false}
                position="top-right"
                autoClose={3000}
              />
            </section>
          </Provider>
          <Footer />
        </main>
      </body>
    </html>
  );
}
