export const ENV = {
  GITHUB_ID: process.env.GITHUB_ID,
  GITHUB_SECRET: process.env.GITHUB_SECRET,
  DISCORD_ID: process.env.AUTH_DISCORD_ID,
  DISCORD_SECRET: process.env.AUTH_DISCORD_SECRET,
  DISCORD_ID_SERVER: process.env.DISCORD_ID_SERVER,
  CLOUDINARY_NAME: process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_KEY: process.env.NEXT_PUBLIC_CLOUDINARY_API_KEY,
}